import React, { useEffect, useRef, useState } from 'react';
import { Activity, AlertTriangle, CheckCircle2, Chrome, CircleDot, Globe2, Loader2, ShieldCheck, Timer, XCircle, Zap } from 'lucide-react';
import { LoadTestConfig } from '../types';

interface BrowserAnalyticsTestProps { config: LoadTestConfig; onChange: (updated: Partial<LoadTestConfig>) => void; }
type ProviderStatus = 'detected' | 'installed-no-request' | 'not-detected';
interface BrowserResult { targetUrl: string; finalUrl: string; title: string; pageLoaded: boolean; loadTimeMs: number; wordpressDetected: boolean; jetpack: { status: ProviderStatus; requests: number; scriptRequests: number }; googleAnalytics: { status: ProviderStatus; requests: number; scriptRequests: number }; otherAnalytics: string[]; requestsObserved: number; consoleErrors: number; blockedRequests: number; notes: string[]; }

const statusLabel: Record<ProviderStatus, string> = { detected: 'REQUEST OBSERVED', 'installed-no-request': 'CODE FOUND · NO REQUEST', 'not-detected': 'NOT DETECTED' };
const statusTone: Record<ProviderStatus, string> = { detected: 'text-[#B4F82C] bg-[#B4F82C]/10 border-[#B4F82C]/30', 'installed-no-request': 'text-amber-300 bg-amber-300/10 border-amber-300/30', 'not-detected': 'text-[#82968B] bg-[#82968B]/10 border-[#82968B]/20' };

export function BrowserAnalyticsTest({ config, onChange }: BrowserAnalyticsTestProps) {
  const [running, setRunning] = useState(false); const [events, setEvents] = useState<string[]>([]); const [result, setResult] = useState<BrowserResult | null>(null); const [error, setError] = useState('');
  const sourceRef = useRef<EventSource | null>(null); const logRef = useRef<HTMLDivElement | null>(null);
  useEffect(() => () => sourceRef.current?.close(), []);
  useEffect(() => { if (logRef.current) logRef.current.scrollTop = logRef.current.scrollHeight; }, [events]);

  const stop = () => { sourceRef.current?.close(); sourceRef.current = null; setRunning(false); setEvents((current) => [...current, 'Browser test stopped.']); };
  const start = () => {
    const target = config.targetUrl.trim(); if (!target) { setError('Enter a public website URL first.'); return; }
    try { const parsed = new URL(target); if (!['http:', 'https:'].includes(parsed.protocol)) throw new Error(); } catch { setError('Use a complete http:// or https:// URL.'); return; }
    sourceRef.current?.close(); setRunning(true); setResult(null); setError(''); setEvents(['Connecting to the ClickHead browser worker…']);
    const source = new EventSource(`/api/browser/stream?targetUrl=${encodeURIComponent(target)}`); sourceRef.current = source;
    source.addEventListener('status', (event) => { try { const payload = JSON.parse((event as MessageEvent).data); setEvents((current) => [...current, payload.message || 'Browser status update.']); } catch { setEvents((current) => [...current, 'Browser status update.']); } });
    source.addEventListener('request', (event) => { try { const payload = JSON.parse((event as MessageEvent).data); setEvents((current) => [...current, payload.message || 'Analytics request observed.']); } catch { /* ignore */ } });
    source.addEventListener('console', (event) => { try { const payload = JSON.parse((event as MessageEvent).data); setEvents((current) => [...current, `Console error: ${payload.message || 'unknown error'}`]); } catch { /* ignore */ } });
    source.addEventListener('complete', (event) => { try { const payload = JSON.parse((event as MessageEvent).data) as BrowserResult; setResult(payload); setEvents((current) => [...current, 'Verification complete.']); } catch { setError('The browser worker returned an invalid result.'); } source.close(); sourceRef.current = null; setRunning(false); });
    source.addEventListener('error', (event) => { if (source.readyState === EventSource.CLOSED) return; try { const payload = JSON.parse((event as MessageEvent).data); setError(payload.message || 'Browser test failed.'); } catch { setError('Browser worker could not be reached.'); } source.close(); sourceRef.current = null; setRunning(false); });
  };

  const providerCard = (name: string, icon: React.ReactNode, provider: BrowserResult['jetpack']) => <div className="bg-[#09150F] border border-[#1A3827] rounded-2xl p-4"><div className="flex items-center justify-between gap-3 mb-3"><div className="flex items-center gap-2.5 min-w-0"><span className="text-[#B4F82C]">{icon}</span><span className="font-black text-sm text-white uppercase tracking-wide truncate">{name}</span></div>{provider.status === 'detected' ? <CheckCircle2 className="w-4 h-4 text-[#B4F82C] shrink-0" /> : provider.status === 'installed-no-request' ? <AlertTriangle className="w-4 h-4 text-amber-300 shrink-0" /> : <CircleDot className="w-4 h-4 text-[#52675B] shrink-0" />}</div><div className={`inline-flex rounded-lg border px-2 py-1 text-[9px] font-black tracking-wider ${statusTone[provider.status]}`}>{statusLabel[provider.status]}</div><div className="grid grid-cols-2 gap-3 mt-4 text-xs font-mono"><div><div className="text-[#63786B] uppercase text-[9px] mb-1">Tracking</div><div className="text-white font-bold">{provider.requests}</div></div><div><div className="text-[#63786B] uppercase text-[9px] mb-1">Scripts</div><div className="text-white font-bold">{provider.scriptRequests}</div></div></div></div>;

  return <div className="space-y-6">
    <section className="bg-[#0C1A12] border-2 border-[#1A3827] rounded-3xl overflow-hidden shadow-xl">
      <div className="p-6 border-b border-[#1A3827]"><div className="flex flex-col lg:flex-row lg:items-end justify-between gap-5"><div><div className="flex items-center gap-2 text-[#B4F82C] text-[10px] font-black uppercase tracking-[0.18em] mb-2"><Chrome className="w-4 h-4" />Browser QA · Analytics Verification</div><h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight">Open the page. Watch the analytics fire.</h2><p className="text-sm text-[#91A69A] mt-2 max-w-2xl leading-6">ClickHead opens your public page in Chromium, executes its JavaScript, watches network traffic, and tells you whether Jetpack, Google Analytics, or other supported analytics actually sent a request.</p></div><div className="flex items-center gap-2 rounded-xl border border-[#1A3827] bg-[#07110C] px-3 py-2 text-[10px] font-bold text-[#91A69A] uppercase tracking-wider shrink-0"><ShieldCheck className="w-4 h-4 text-[#B4F82C]" /> Authorized public targets only</div></div></div>
      <div className="p-6 space-y-5"><div><label className="block text-[10px] font-black uppercase tracking-widest text-[#789083] mb-2">Public page URL</label><div className="flex flex-col sm:flex-row gap-3"><div className="flex-1 relative"><Globe2 className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-[#60766A]" /><input value={config.targetUrl} onChange={(event) => onChange({ targetUrl: event.target.value })} onKeyDown={(event) => { if (event.key === 'Enter' && !running) start(); }} placeholder="https://example.com/article" className="w-full h-12 rounded-xl border border-[#244630] bg-[#07110C] pl-10 pr-4 text-sm text-white font-mono outline-none focus:border-[#B4F82C] transition-colors" /></div>{!running ? <button onClick={start} className="h-12 px-6 rounded-xl bg-[#B4F82C] text-black text-xs font-black uppercase tracking-wider hover:brightness-105 active:scale-[0.98] transition-all flex items-center justify-center gap-2 cursor-pointer"><Zap className="w-4 h-4" />Run Browser Test</button> : <button onClick={stop} className="h-12 px-6 rounded-xl border border-red-500/30 bg-red-500/10 text-red-300 text-xs font-black uppercase tracking-wider hover:bg-red-500/15 transition-all flex items-center justify-center gap-2 cursor-pointer"><XCircle className="w-4 h-4" />Stop Test</button>}</div>{error && <div className="mt-3 rounded-xl border border-red-500/20 bg-red-500/5 px-4 py-3 text-xs text-red-300 flex items-center gap-2"><AlertTriangle className="w-4 h-4 shrink-0" />{error}</div>}</div><div className="grid grid-cols-1 md:grid-cols-3 gap-3 text-xs"><Feature icon={<Chrome />} title="Real Chromium" body="Normal browser JavaScript execution." /><Feature icon={<Activity />} title="Network inspection" body="See actual analytics requests." /><Feature icon={<ShieldCheck />} title="Safe by default" body="Private-network requests are blocked." /></div></div>
    </section>
    {(running || events.length > 0) && <section className="bg-[#050C08] border border-[#1A3827] rounded-3xl overflow-hidden"><div className="px-5 py-4 border-b border-[#1A3827] flex items-center justify-between"><div className="flex items-center gap-2 text-white text-xs font-black uppercase tracking-wider"><span className="inline-flex w-2 h-2 rounded-full bg-[#B4F82C]" />Browser Telemetry</div>{running && <div className="flex items-center gap-2 text-[10px] font-mono text-[#B4F82C]"><Loader2 className="w-3.5 h-3.5 animate-spin" />RUNNING</div>}</div><div ref={logRef} className="h-44 overflow-y-auto p-4 font-mono text-[11px] leading-5 text-[#90A89A] space-y-1">{events.map((event, index) => <div key={`${index}-${event}`}><span className="text-[#435B4C] mr-2">{String(index + 1).padStart(3, '0')}</span><span className={/error|blocked/i.test(event) ? 'text-amber-300' : /analytics|complete/i.test(event) ? 'text-[#B4F82C]' : ''}>{event}</span></div>)}</div></section>}
    {result && <section className="space-y-4"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><div className="text-[10px] font-black uppercase tracking-[0.18em] text-[#789083]">Verification Result</div><h3 className="text-xl font-black text-white mt-1">{result.title || result.finalUrl}</h3></div><div className="flex items-center gap-2 text-xs font-mono text-[#91A69A]"><Timer className="w-4 h-4" />{result.loadTimeMs}ms total</div></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3"><Metric label="Page" value={result.pageLoaded ? 'Loaded' : 'Failed'} icon={result.pageLoaded ? <CheckCircle2 /> : <XCircle />} good={result.pageLoaded} /><Metric label="WordPress" value={result.wordpressDetected ? 'Detected' : 'Not detected'} icon={<Globe2 />} good={result.wordpressDetected} /><Metric label="Requests" value={String(result.requestsObserved)} icon={<Activity />} good /><Metric label="Console errors" value={String(result.consoleErrors)} icon={<AlertTriangle />} good={result.consoleErrors === 0} /></div><div className="grid grid-cols-1 md:grid-cols-2 gap-4">{providerCard('Jetpack Stats', <Activity className="w-4 h-4" />, result.jetpack)}{providerCard('Google Analytics', <Globe2 className="w-4 h-4" />, result.googleAnalytics)}</div>{result.otherAnalytics.length > 0 && <div className="bg-[#09150F] border border-[#1A3827] rounded-2xl p-4"><div className="text-[10px] font-black uppercase tracking-widest text-[#789083] mb-2">Other analytics observed</div><div className="flex flex-wrap gap-2">{result.otherAnalytics.map((name) => <span key={name} className="px-2.5 py-1 rounded-lg bg-[#B4F82C]/10 border border-[#B4F82C]/20 text-[#B4F82C] text-xs font-bold">{name}</span>)}</div></div>}<div className="bg-[#0C1A12] border border-[#1A3827] rounded-2xl p-5"><div className="text-[10px] font-black uppercase tracking-widest text-[#789083] mb-3">What this means</div><ul className="space-y-2 text-xs text-[#9AAEA1] leading-5">{result.notes.map((note) => <li key={note} className="flex gap-2"><span className="text-[#B4F82C] mt-0.5">•</span><span>{note}</span></li>)}</ul></div></section>}
  </div>;
}

function Feature({ icon, title, body }: { icon: React.ReactNode; title: string; body: string }) { return <div className="rounded-xl border border-[#1A3827] bg-[#09150F] p-3 flex gap-3"><span className="text-[#B4F82C] mt-0.5">{React.cloneElement(icon as React.ReactElement<{ className?: string }>, { className: 'w-4 h-4' })}</span><div><div className="font-bold text-white">{title}</div><div className="text-[#71877A] mt-1">{body}</div></div></div>; }
function Metric({ label, value, icon, good }: { label: string; value: string; icon: React.ReactNode; good: boolean }) { return <div className="bg-[#0C1A12] border border-[#1A3827] rounded-2xl p-4"><div className="flex items-center justify-between mb-3"><span className="text-[9px] uppercase tracking-widest font-black text-[#6F8578]">{label}</span><span className={good ? 'text-[#B4F82C]' : 'text-red-300'}>{React.cloneElement(icon as React.ReactElement<{ className?: string }>, { className: 'w-4 h-4' })}</span></div><div className="text-lg font-black text-white">{value}</div></div>; }
