import React, { useState, useRef, useEffect } from 'react';
import { AggregatedMetrics, LoadTestConfig, RequestMetric, TerminalLogEntry } from '../types';
import { TrafficSimulator } from '../utils/trafficSimulator';
import { Play, Square, RotateCcw, Activity, CheckCircle, AlertTriangle, XCircle, Gauge, Cpu, Zap, Radio } from 'lucide-react';

interface LiveSimulatorProps { config: LoadTestConfig; onSimulationStateChange?: (isRunning: boolean) => void; }

const emptyMetrics: AggregatedMetrics = { totalSent:0, completed:0, successful:0, redirects:0, clientErrors:0, serverErrors:0, networkErrors:0, elapsedSeconds:0, currentRps:0, avgRps:0, avgDurationMs:0, minDurationMs:0, maxDurationMs:0, p50Ms:0, p90Ms:0, p95Ms:0, p99Ms:0, totalBytes:0 };

export const LiveSimulator: React.FC<LiveSimulatorProps> = ({ config, onSimulationStateChange }) => {
  const [isRunning,setIsRunning]=useState(false); const [metrics,setMetrics]=useState<AggregatedMetrics>(emptyMetrics); const [logs,setLogs]=useState<TerminalLogEntry[]>([]); const [filterLevel,setFilterLevel]=useState<'ALL'|'SUCCESS'|'ERROR'>('ALL');
  const simulatorRef=useRef<TrafficSimulator|null>(null); const terminalRef=useRef<HTMLDivElement>(null); const shouldFollowLogs=useRef(true);

  const startSimulation=()=>{ if(isRunning)return; setLogs([]);setMetrics(emptyMetrics);setIsRunning(true);onSimulationStateChange?.(true); const sim=new TrafficSimulator(config,{onMetric:(_metric,current)=>setMetrics(current),onLog:(log)=>setLogs(prev=>[...prev,log].slice(-400)),onComplete:(final)=>{setMetrics(final);setIsRunning(false);onSimulationStateChange?.(false);}}); simulatorRef.current=sim;sim.start(); };
  const stopSimulation=()=>{ simulatorRef.current?.stop();setIsRunning(false);onSimulationStateChange?.(false); };
  const resetAll=()=>{stopSimulation();setLogs([]);setMetrics(emptyMetrics);};

  useEffect(()=>{
    const el=terminalRef.current; if(!el)return;
    if(shouldFollowLogs.current) el.scrollTop=el.scrollHeight;
  },[logs]);

  const handleTerminalScroll=()=>{ const el=terminalRef.current; if(!el)return; const distanceFromBottom=el.scrollHeight-el.scrollTop-el.clientHeight; shouldFollowLogs.current=distanceFromBottom<24; };

  const progressPercent=config.totalRequests>0?Math.min(100,Math.round((metrics.completed/config.totalRequests)*100)):0;
  const successPercent=metrics.totalSent>0?((metrics.successful/metrics.totalSent)*100).toFixed(1):'100.0';
  const filteredLogs=logs.filter(l=>filterLevel==='ALL'||(filterLevel==='SUCCESS'?l.level==='SUCCESS':l.level==='ERROR'));

  return <div className="bg-[#0C1A12] border-2 border-[#1B3827] rounded-3xl p-5 sm:p-7 shadow-xl space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-4 pb-4 border-b border-[#1B3827]"><div className="flex items-center gap-3"><div className="relative"><div className={`w-3.5 h-3.5 rounded-full ${isRunning?'bg-[#B4F82C] animate-ping':'bg-[#254C34]'}`}/><div className={`absolute inset-0 w-3.5 h-3.5 rounded-full ${isRunning?'bg-[#B4F82C]':'bg-[#254C34]'}`}/></div><div><h3 style={{fontFamily:"'Syne', 'Plus Jakarta Sans', sans-serif"}} className="text-base sm:text-lg font-black text-white flex items-center gap-2 uppercase tracking-tight">HTTP REQUEST TELEMETRY<span className={`text-[11px] px-2.5 py-0.5 rounded-full font-mono font-bold border ${isRunning?'bg-[#152E20] text-[#B4F82C] border-[#B4F82C]':'bg-[#112419] text-[#9BB0A3] border-[#1E3E2B]'}`}>{isRunning?'RUNNING':'READY'}</span></h3><p className="text-xs text-[#9BB0A3] font-mono mt-0.5">Target: <span className="text-[#B4F82C] font-semibold truncate max-w-xs inline-block align-bottom">{config.targetUrl||'No target selected'}</span></p></div></div><div className="flex items-center gap-2">{!isRunning?<button id="btn-start-simulation" onClick={startSimulation} className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-[#B4F82C] hover:bg-[#C8FF47] text-black font-extrabold text-xs transition-all shadow-md shadow-[#B4F82C]/20 cursor-pointer uppercase tracking-wider"><Play className="w-3.5 h-3.5 fill-black"/><span>Start Dispatch</span></button>:<button id="btn-stop-simulation" onClick={stopSimulation} className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-red-600 hover:bg-red-500 text-white font-extrabold text-xs transition-all shadow-md shadow-red-600/30 cursor-pointer uppercase tracking-wider"><Square className="w-3.5 h-3.5 fill-white"/><span>Stop</span></button>}<button id="btn-reset-simulation" onClick={resetAll} disabled={isRunning} className="p-2.5 rounded-xl bg-[#07110C] hover:bg-[#142C1E] text-[#9BB0A3] hover:text-white border border-[#1E3E2B] disabled:opacity-40 transition-colors cursor-pointer" title="Reset telemetry"><RotateCcw className="w-4 h-4"/></button></div></div>
    <div className="space-y-2"><div className="flex items-center justify-between text-xs font-mono"><span className="text-[#E8EDE0] flex items-center gap-1.5 font-bold uppercase tracking-wider"><Radio className="w-3.5 h-3.5 text-[#B4F82C]"/>Transmission Progress</span><span className="text-[#B4F82C] font-black">{metrics.completed} / {config.totalRequests} ({progressPercent}%)</span></div><div className="w-full h-3 bg-[#07110C] rounded-full overflow-hidden border border-[#1E3E2B]"><div className="h-full bg-[#B4F82C] transition-all duration-200 ease-out" style={{width:`${progressPercent}%`}}/></div></div>
    <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">{[['200 OK Hits',metrics.successful],['Throughput',`${metrics.currentRps.toFixed(1)} RPS`],['Avg Latency',`${metrics.avgDurationMs} ms`],['Elapsed',`${metrics.elapsedSeconds.toFixed(1)} s`]].map(([label,value],i)=><div key={String(label)} className="bg-[#07110C] border-2 border-[#1E3E2B] rounded-2xl p-4"><div className="text-[11px] font-bold text-[#9BB0A3] uppercase tracking-wider">{label}</div><div className="text-2xl font-black font-mono text-[#B4F82C] mt-1">{value}</div><div className="text-[10px] text-[#9BB0A3] font-mono mt-0.5">{i===0?`${successPercent}% success`:i===1?`${config.concurrency} workers`:i===2?`P95 ${metrics.p95Ms}ms`:`${(metrics.totalBytes/1024).toFixed(1)} KB read`}</div></div>)}</div>
    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs"><div className="bg-[#07110C] border border-[#1E3E2B] rounded-2xl p-4"><div className="font-extrabold text-white uppercase tracking-wider mb-2.5">Latency Percentiles</div><div className="grid grid-cols-4 gap-2 text-center font-mono">{[['P50',metrics.p50Ms],['P90',metrics.p90Ms],['P95',metrics.p95Ms],['P99',metrics.p99Ms]].map(([l,v])=><div key={String(l)} className="p-2.5 bg-[#0C1A12] rounded-xl border border-[#1E3E2B]"><span className="text-[10px] text-[#9BB0A3] block uppercase font-bold">{l}</span><span className="font-black text-white">{v}ms</span></div>)}</div></div><div className="bg-[#07110C] border border-[#1E3E2B] rounded-2xl p-4"><div className="font-extrabold text-white uppercase tracking-wider mb-2.5">Response Breakdown</div><div className="grid grid-cols-4 gap-2 text-center font-mono"><div className="p-2.5 bg-[#0C1A12] rounded-xl border border-[#1E3E2B]"><span className="text-[10px] text-[#B4F82C] block font-bold uppercase">2xx</span><span className="font-black text-[#B4F82C]">{metrics.successful}</span></div><div className="p-2.5 bg-[#0C1A12] rounded-xl border border-[#1E3E2B]"><span className="text-[10px] text-yellow-400 block font-bold uppercase">3xx</span><span className="font-black text-yellow-300">{metrics.redirects}</span></div><div className="p-2.5 bg-[#0C1A12] rounded-xl border border-[#1E3E2B]"><span className="text-[10px] text-rose-400 block font-bold uppercase">4xx/5xx</span><span className="font-black text-rose-300">{metrics.clientErrors+metrics.serverErrors}</span></div><div className="p-2.5 bg-[#0C1A12] rounded-xl border border-[#1E3E2B]"><span className="text-[10px] text-[#9BB0A3] block font-bold uppercase">Network</span><span className="font-black text-white">{metrics.networkErrors}</span></div></div></div></div>
    <div className="bg-[#07110C] border-2 border-[#1E3E2B] rounded-2xl overflow-hidden font-mono text-xs shadow-inner"><div className="bg-[#0A1810] px-4 py-2.5 border-b border-[#1E3E2B] flex items-center justify-between"><div className="flex items-center gap-2"><div className="w-2.5 h-2.5 rounded-full bg-[#B4F82C]"/><span className="text-white font-sans font-bold text-[11px] uppercase tracking-wider">Live HTTP Request Log</span></div><div className="flex items-center gap-1.5 font-sans"><button onClick={()=>setFilterLevel('ALL')} className={`px-2.5 py-1 rounded-lg text-[10px] font-bold cursor-pointer uppercase tracking-wider ${filterLevel==='ALL'?'bg-[#B4F82C] text-black':'text-[#9BB0A3] hover:text-white'}`}>All ({logs.length})</button><button onClick={()=>setFilterLevel('SUCCESS')} className={`px-2.5 py-1 rounded-lg text-[10px] font-bold cursor-pointer uppercase tracking-wider ${filterLevel==='SUCCESS'?'bg-[#183624] text-[#B4F82C] border border-[#27533B]':'text-[#9BB0A3] hover:text-white'}`}>Success</button><button onClick={()=>setFilterLevel('ERROR')} className={`px-2.5 py-1 rounded-lg text-[10px] font-bold cursor-pointer uppercase tracking-wider ${filterLevel==='ERROR'?'bg-red-950 text-red-300 border border-red-800':'text-[#9BB0A3] hover:text-white'}`}>Fails</button></div></div><div ref={terminalRef} onScroll={handleTerminalScroll} className="p-4 h-64 overflow-y-auto space-y-1.5 select-text bg-[#050C08]">{filteredLogs.length===0?<div className="text-[#567362] py-8 text-center italic font-sans text-xs">Start a dispatch to stream live HTTP events.</div>:filteredLogs.map((log,idx)=>{let colorClass='text-[#E8EDE0]';if(log.level==='SUCCESS')colorClass='text-[#B4F82C] font-semibold';if(log.level==='ERROR')colorClass='text-rose-400 font-semibold';if(log.level==='WARN')colorClass='text-amber-400';return <div key={`${log.timestamp}-${idx}`} className="leading-relaxed flex items-start gap-2 text-[11px]"><span className="text-[#43634F] shrink-0">[{log.timestamp}]</span><span className={colorClass}>{log.message}</span></div>})}</div></div>
  </div>;
};
